config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

 

  get 'users/show'

  get 'users/new'

  get 'users/create'

  get 'toppages/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  
  get 'login' ,to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only:[:show,:new,:create]
  resources :helpers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/helper.rb
class Helper < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255}
  validates :status, presence: true, length: {maximum: 15}
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50}
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  has_many :helpers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
     redirect_to login_url
    end
  end
  
  def count(user)
    @count_helpers = user.helpers.count
  end
  
end

app/controllers/helpers_controller.rb
class HelpersController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only:[:index,:show,:edit,:update,:destroy]
  def index
    @helpers = Helper.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def show
    set_helper
  end
  
  def new
    @helper = Helper.new
  end
  
  def create
    @helper = current_user.helpers.build(helper_params)
    
    if @helper.save
       flash[:success] = '投稿されました'
       redirect_to @helper
    else
      @helper = current_user.helpers.order('created_at DESC').page(params[:page])
      
      flash.now[:danger] = '投稿されませんでした'
      render :new
    end
  end
  
  def edit
    set_helper
  end
  
  def update
    set_helper
    if @helper.update(helper_params)
       flash[:success] = '更新されました'
       redirect_to @helper
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
    
  end
  
  def destroy
    set_helper
    @helper.destroy
    flash[:success] = '削除されました'
    redirect_to helpers_url
    
    
  end
  
  private
  
  def set_helper
    @helper = Helper.find(params[:id])
  end
  
  #strong parameter
  
  def helper_params
    params.require(:helper).permit(:content,:status)
  end
  
  def correct_user
    @helper = current_user.helpers.find_by(id: params[:id])
    unless @helper
     redirect_to root_url
    end
    
  end
  
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = 'ログインしました'
      redirect_to @user
    else
      flash.now[:danger] ='ログインに失敗しました'
      render 'new'
    end
  end
  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
   
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @helpers = current_user.helpers.order('created_at DESC').page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only:[:index,:show]
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    
    
    unless current_user == @user
     redirect_to root_url
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
       flash[:success] = '登録しました'
       redirect_to @user
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
    
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    
  end
  
  def logged_in?
    !!current_user
    
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/helpers/_form.html.erb
<div class="row">
  <div class="col-xs-6">

  <%= form_for(helper) do |f| %>
   <% if helper.errors.any? %>
    <div class="alert alert-">
      <ul>
        <% helper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    
    
    
    </div>
    <% end %>
  
   <div class="form-group">
    <%= f.label :status, 'ステータス' %>
    <%= f.text_field :status, class: 'form-control' %>
   </div>
  
   <div class="form-group">
    <%= f.label :content, 'ヘルパー' %>
    <%= f.text_field :content, class: 'form-control' %>
   </div>
  
    <%= f.submit '投稿', class: 'btn btn-primary' %>
  
  <% end %>
 </div>
</div>

app/views/helpers/_helpers.html.erb
<ul class="media-list">
  <% helpers.each do |helper| %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(helper.user, { size: 50 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to helper.user.name, user_path(helper.user) %> <span class="text-muted">posted at <%= helper.created_at %></span>
        </div>
        <div>
          <p><%= helper.content %></p>
        </div>
        <div>
          <% if current_user == helper.user %>
            <%= link_to "Delete", helper, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate helpers %>
</ul>

app/views/helpers/edit.html.erb
<h1>id:<%= @helper.id %>の編集ページ</h1>

<%= render 'form', helper: @helper %>

app/views/helpers/index.html.erb
<h1>ヘルパー　一覧</h1>

<% if @helpers.any? %>
 <table class="table table-striped">
   <thead>
     <tr>
       <th>id</th>
       <th>ステータス</th>
       <th>ヘルパー</th>
     </tr>
   </thead>
   <tbody>
     <% @helpers.each do |helper| %>
     <tr>
       <td><%= link_to helper.id, helper %></td>
       <td><%= helper.status %></td>
       <td><%= helper.content %></td>
     </tr>
     <% end %>
   </tbody>
   
 </table>
 <div>
  <%= paginate @helpers %>
 </div>
 <% end %>
<%= link_to '新規作成ページ', new_helper_path, class: "btn btn-primary" %>

app/views/helpers/new.html.erb
<h1>作成ページ</h1>

<%= render 'form', helper: @helper %>

app/views/helpers/show.html.erb
<h1>id:<%= @helper.id %> 詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @helper.id %></td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td><%= @helper.status %></td>
  </tr>
  <tr>
    <th>ヘルパー</th>
    <td><%= @helper.content %></td>
  </tr>
  
  
</table>

<%= link_to '編集ページ', edit_helper_path(@helper), class: 'btn btn -default' %>
<%= link_to '削除する',@helper,method: :delete, data:{confirm: '本当に削除してよろしいですか？'}, class: 'btn btn-danger' %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
 <div class="alert alert-warning">
   <ul>
     <% model.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
   </ul>
   
 </div>
<% end %>

app/views/layouts/_flash_helpers.html.erb
<% flash.each do |helper_type,helper| %>
<div class="alert alert-<%= helper_type %>"><%= helper %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">HelperBoard</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to  '新規ヘルパーの投稿', new_helper_path %></li>
                <li><%= link_to 'My profile', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path,method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
            
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>HelperBoard</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_helpers' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
 <div class="row">
  <div class="col-xs-8">
    <%= render 'helpers/helpers', helpers: @helpers %>
  </div>
 </div>
<% else %>
<div class="center jumbotron">
  <div class="text-center">
    <h1>Welcome to the HelperBoard</h1>
    
    
    <%= link_to 'Sign up now !!', signup_path, class: 'btn btn-lg btn-primary' %>
  </div>
  
  
  
</div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li><%= link_to 'toppages', root_path %></li>
      
    </ul>
  </div>
</div>